name: Elixir CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.18-slim
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y ca-certificates
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run tests
      run: mix test
